name: DO_4_Backend. Lint,Test,Build & Upload to ECR.
run-name: ${{ github.sha }} Backend for DO_4 
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runs-on'
        required: true
        default: 'warning'
        type: choice
        options:
        - ubuntu-latest
        - self-hosted
  push:
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'

jobs:
  checkout-test-build-upload-DO4:
    runs-on: ${{ inputs.runner }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install python3
          sudo apt-get install python3-pip
          python3 -m pip install --upgrade pip
        shell: bash

      - name: Install Dependencies
        run: | 
          python3 -m pip install -r app/requirements.txt
          python3 -m pip install -r app/requirements_dev.txt
        shell: bash

      - name: Lint with flake8
        run: flake8 app/

      - name: Run Tests
        run: python3 -m pytest app/tests/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: backend
          IMAGE_TAG_1: latest
          IMAGE_TAG_2: ${{ github.sha }}
        run: |
          cd app/ && docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG_1 $REGISTRY/$REPOSITORY:$IMAGE_TAG_2.
          docker push --all-tags $REGISTRY/$REPOSITORY
          


