name: DO_4_Backup. Create & Upload to S3
run-name: ${{ github.sha }} Backup for DO_4
on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runs-on'
        required: true
        default: 'warning'
        type: choice
        options:
        - ubuntu-latest
        - self-hosted

jobs:
  backup-upload-S3:
    runs-on: ${{ inputs.runner }}
    
    permissions:
      contents: read
      actions: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install jq
      run: sudo apt-get install jq

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }} 

    - name: Check and download versions.json
      run: |
        S3_BUCKET="devops-intern-ilovekharkiv"
        FILE_KEY="versions.json"
                      
        if aws s3api head-object --bucket "$S3_BUCKET" --key "$FILE_KEY" 2>/dev/null; then
          echo "File exists in S3. Downloading..."
          aws s3 cp "s3://$S3_BUCKET/$FILE_KEY" "./backup/$FILE_KEY"
          echo "File downloaded successfully!"
        else
          echo "File does not exist in S3. Moving forward."
        fi
        ls -lh

    - name: Launch backup.sh using version.json from S3 bucket
      run: |
        if [ -f backup/versions.json ]; then
         VERSION=$(jq -r '.[] | "\(.version)\t\(.date)"' backup/versions.json | sort -k2 -r | head -n1 | cut -f1)
        fi
        if [ -z "$VERSION" ]; then
         VERSION="1.0.0"
        fi
        chmod +x ./backup.sh
        echo "$VERSION"
        ./backup.sh $VERSION 

    - name: Upload to S3!
      id: upload_to_s3
      run: aws s3 sync backup/ s3://devops-intern-ilovekharkiv  
