name: DO_4_Frontend. Checkout,Test,Build & Upload to ECR.
run-name: ${{ github.sha }} FE for DO_4 
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runs-on'
        required: true
        default: 'warning'
        type: choice
        options:
        - ubuntu-latest
        - self-hosted
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  checkout-test-build-upload-DO4:
    runs-on: ${{ inputs.runner }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install chromium-browser
        shell: bash

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: frontend/

      - name: Lint with npm
        run: npm run lint
        working-directory: frontend/

      - name: Run Tests
        run: |
          npm ci
          npm run test:ci
        working-directory: frontend/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: frontend
          IMAGE_TAG: latest
        run: |
          cd frontend/ && docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
