name: DO_4_Nginx. Build & Upload.
run-name: ${{ github.sha }} Nginx for DO_4
on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runs-on'
        required: true
        default: 'warning'
        type: choice
        options:
        - ubuntu-latest
        - self-hosted
  push:
    paths:
      - 'nginx/**'
  pull_request:
    paths:
      - 'nginx/**'
  
jobs:
  nginx-build-upload-DO4:
    runs-on: ${{inputs.runner || 'ubuntu-latest'}} # either self-hosted or github runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: nginx
          IMAGE_TAG: latest
        run: |
          cd nginx/ && docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


